---
- name: Create postgres namespace
  kubernetes.core.k8s:
    name: postgres
    api_version: v1
    kind: Namespace
    state: present

- name: Create Postgres secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: postgres-credentials
        namespace: postgres
      data:
        postgres-password: "{{ postgres.password | b64encode }}"

- name: Add Bitnami chart repo
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Deploy Postgres
  kubernetes.core.helm:
    name: postgres
    chart_ref: bitnami/postgresql
    release_namespace: postgres
    chart_version: 12.5.8
    release_values: "{{ lookup('template', 'values.postgres.yml.j2') | from_yaml }}"

- name: Create users
  community.postgresql.postgresql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    login_host: "127.0.0.1"
    login_password: "{{ postgres.password }}"
  loop: 
    - name: coder
      password: "{{ coder.db.password }}"
    - name: "{{ nextcloud.db.username }}"
      password: "{{ nextcloud.db.password }}"

- name: Create databases
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    owner: "{{ item.owner }}"
    encoding: UTF-8
    login_host: "127.0.0.1"
    login_password: "{{ postgres.password }}"
  loop: 
    - name: coder
      owner: coder
    - name: "{{ nextcloud.db.name }}"
      owner: "{{ nextcloud.db.username }}"