# Workflow for running terraform and ansible
# on a github hosted agent

name: Build and deploy

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2

      - name: Terraform Plan
        run: |
          export TF_TOKEN_app_terraform_io=$TCLOUD_TOKEN
          export TF_VAR_hcloud_token=$HCLOUD_TOKEN
          echo $SSH_PRIVATE_KEY > ssh_private_key
          chmod 600 ssh_private_key
          echo $SSH_PUBLIC_KEY > ssh_public_key
          export TF_VAR_ssh_public_key=${{ github.workspace }}/k8s/ssh_public_key
          export TF_VAR_ssh_private_key=${{ github.workspace }}/k8s/ssh_private_key
          env
          pwd
          echo ${{ github.workspace }}
          ls -als
          terraform init
          terraform plan
        working-directory: ./k8s
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          TCLOUD_TOKEN: ${{ secrets.TCLOUD_TOKEN }}

      # Ask for confirmation before applying
      # - name: Terraform Apply
      #   run: terraform apply
      #   working-directory: ./k8s

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt install ansible

      - name: Get secret file named ansible-vault.pass
        run: |
          echo ${{ secrets.ANSIBLE_VAULT_PASS }} > ansible-vault.pass
          chmod 600 ansible-vault.pass

      - name: Ansible Playbook
        run: ansible-playbook configure.yml --vault-password-file=ansible-vault.pass  -e 'ansible_python_interpreter=/usr/bin/python3'
        working-directory: ./ansible